version: '3.8'
name: agropulse
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.14
    container_name: agropulse-redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9092:9092"
      - "9644:9644"

  # Aquí sumaremos el "Worker" (Simulador IoT) más adelante
